AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'Boltdir/**/*'
    - 'vendor/**/*'
    - 'vendored/**/*'
    - 'acceptance/vendor/**/*'
    - 'modules/**/*'
    - 'docs/**/*'
    - 'site-modules/**/*'
    - 'tasks/**/*'

# Checks for if and unless statements that would fit on one line if written as a
# modifier if/unless.
Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/IfUnlessModifier:
  Enabled: false

Style/AccessModifierDeclarations:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/StderrPuts:
  Enabled: false

Style/ExponentialNotation:
  Enabled: true

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/HeredocIndentation:
  Enabled: false

Layout/ClosingHeredocIndentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Style/GuardClause:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/SlicingWithRange:
  Enabled: false

Style/RedundantFetchBlock:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/AccessorGrouping:
  Enabled: true

# Disabled due to a bug in Rubocop that raises an exception when accessors
# are assigned using a splat operator
# https://github.com/rubocop-hq/rubocop/issues/8257
Style/BisectedAttrAccessor:
  Enabled: false

Style/RedundantAssignment:
  Enabled: true

# Disable nearly all Metrics checks. These seem better off left to judgement.

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Lint/SuppressedException:
  Exclude:
    - lib/bolt/shell/bash.rb

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: false

# Enforce LF line endings, even when on Windows
Layout/EndOfLine:
  EnforcedStyle: lf

Layout/HashAlignment:
  EnforcedHashRocketStyle: [key, table]
  EnforcedColonStyle: [key, table]

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

