sudo: required
language: ruby
cache: bundler
services:
- docker
rvm:
- 2.5
env:
  global:
    - REGISTRY_HOST=pcr-internal.puppet.net
    - DOCKER_REGISTRY=pe-and-platform
    - secure: "KF0rqrducC1oom9XpWsOsO/opdvYn9oXmYoavJbqJ3FcwkjmBD3//vGyDaguZ62p8BwUxK5xX99/HnrPbBC/KxBPIoUZsAPoVp9FK4wOlu0UkrvXLMJKeQ8XTxihtEy1kpXfp6+G98R+a1GoQYsZ4u6h9+cOMM2Ml7UesqP9PfSeN9hxJEHkKsaiAoYR8QWiXSBp00mvN11grp+sWDxCOB5wPvc1E5qhCZcaYDPYAIDiGBENCo7YW/GBqIjrV3ZNeNxbsFUT9mP6WVnh+X206u98ajEs1JYYAKEdntkb3DF4t1rSzov0t3YS2C1L+1PntZ5QhrKlW4DoO92p0qv3TitUA4F+6+5eaeGMk9FFL88Zc+Qr240u8Or1K+RDxm7HzerqW5CUYQ6omvdPzQRJ1qYQMDO3rT/Hgxst5hc5x9wDyosPCyndaJezwEg8iAz6C9xpXSmmGILZuZCVf0xSVT0PlgJtwM+zEYLITFgdlm03Xb+aYeWXqMBtvsnZNZQu+kjpjyJ+CxCt/+UA+row4/wgA/rcnf4UBiRGNrd1vd7ar03Jb8btO1ti2iEuNzRPkP0ZX9yOSt5/pmRCrSnIJCEIwCWFnowFMNvlz70oKPkCkcpXHLUY2g4DJVXzmTfXu9XQZzXPd9YSpRHga5YsaxxYO6obaoROr6GTlvVtfD8="
before_script:
- docker-compose -f spec/docker-compose.yml up -d --build
- eval `ssh-agent`
- cat Gemfile.lock
- bundle exec r10k puppetfile install

script:
- bundle exec rake travisci
- bundle exec rubocop
- |
  status=0
  pushd bolt-modules/boltlib
  if ! bundle exec rake spec; then
    status=1
  fi
  popd
  if [ $status -eq 1 ]; then
    false
  fi
- |
  status=0
  for i in 'canary' 'aggregate' 'puppetdb_fact'; do
    pushd modules/$i
    if ! bundle exec rake spec; then
      status=1
    fi
    popd
  done
  # fail this step if there were any failures
  if [ $status -eq 1 ]; then
    false
  fi
- bundle exec rake puppetserver
after_script:
- docker-compose -f spec/docker-compose.yml logs
deploy:
  provider: script
  on:
    # deploy the master branch or tag pushes
    condition: $TRAVIS_BRANCH == "master" || -n $TRAVIS_TAG
  script: bash scripts/deploy.sh
notifications:
  email: false
  hipchat:
    rooms:
      secure: j1c64TomsD45XGBnv+0AaLPBFacg3hWAs7p2Qo+AYRrXXT2lLyqYlOCUo4oek9r7+SQ4nHbGjxC59o6g3YTF5obsQosLpb9EdgmVaS14khnBlb2Mvo2fKoRZ3YiKQQ6L+TFE9NiQ3XC4ccvfXrwSjXZsByVJiPaDieXQr83qE6xdsNGN9jSW2fJ+Qt90TXd3TBabu2pTxiAZVVmZYa409jmTsDRpeZXic7Om4jj4MYaFkHWl1sakktIijgN5vvscqxe9cn0JgtcX5ZQo7UoZ1tH+8dko5IB1s04CF1K2AJytb8Jt/tIx1z8khwaGiPNGHJby9lndKGrU1lm1jA9IkqaY8L2iHNN4mivpf5PpvV82QfJcc+JQgVA6xCMYOO/RimeyNGeHcMzd7dQuOneSzMkeLarLZ1k6ayYDxuDwzgjl4P/sM7V0rCsyDfNL/fTNdt9Ix7GBWHyL7aQLeSxksD7RA3et6q8OcwklMVVVt4+xyYR2Ui8hyRc7KTHEH5Ff/NpgpAQmwl47BKMz9nwf6wey8HqWXuoyA+xkwq3fXM6Ifh+RFw12MwoylcKo3TB8hH66hpn19XltHkvfvDNxo+Xc4aScZqZhPPN0dJ6h6P65jUbPM+PdfrZ3V/Nuz59LQ93CmlcQOwcP0a7KUGRq38iqWHDgoauQvp44iGwAHOc=
    template:
    - '<a href="https://github.com/%{repository_slug}">%{repository_name}</a>#<a href="%{build_url}">%{build_number}</a>
      (<a href="%{compare_url}">%{branch} - %{commit} : %{author}</a>): %{message}'
    format: html
