# See https://docs.travis-ci.com/user/languages/ruby/
sudo: false
language: ruby
rvm:
  - 2.4.1
  - 2.1

before_install:
  - gem update bundler

install:
  - bundle config --local path .bundle
  - bundle install --jobs=3 --retry=3

before_script:
  - ruby -v
  - gem -v
  - bundle -v
  - cat Gemfile.lock

script:
  - bundle exec rake spec
