# See https://www.appveyor.com/docs/lang/ruby/
version: 0.1.0.{build}-{branch}
cache:
  - .bundle

matrix:
  fast_finish: true

configuration:
  - Agentfull
  - Agentless

environment:
  BOLT_WINRM_USER: roddypiper
  BOLT_WINRM_HOST: localhost
  BOLT_WINRM_PORT: 5985
  BOLT_WINRM_SSL_PORT: 5986
  BOLT_WINRM_SMB_PORT: 445
  RUBY_VERSION: 25

install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - bundle config --local path .bundle
  - bundle install --jobs 3 --retry 3

build: off

for:
  -
    matrix:
      only:
        - configuration: Agentless

    environment:
      BOLT_WINDOWS: true

    before_test:
      - ps: |
          ruby -v
          gem -v
          bundle -v
          type Gemfile.lock
          . .\ci.ps1
          Install-Puppetfile
          Set-WinRMHostConfiguration

    test_script:
      - bundle exec rake appveyor
      - ps: |
          $test_fail = 0
          $mods = ("boltlib", "ctrl", "file", "system")
          Get-ChildItem bolt-modules -Directory -Include $mods | foreach {
            cd $_.FullName;
            $test_output = bundle exec rake spec
            $r = $LASTEXITCODE
            Write-Output $test_output
            if($r) {
              $test_fail = $r
            }
          }
          if($test_fail) { throw "core module tests failed" }
          cd ../..
      - ps: |
          $test_fail = 0
          $mods = ("canary", "aggregate", "puppetdb_fact")
          Get-ChildItem modules -Directory -Include $mods | foreach {
            cd $_.FullName;
            $test_output = bundle exec rake spec
            $r = $LASTEXITCODE
            Write-Output $test_output
            if($r) {
              $test_fail = $r
            }
          }
          if($test_fail) { throw "module tests failed" }
          cd ../..

  -
    matrix:
      exclude:
        - configuration: Agentfull
          RUBY_VERSION: 23
        - configuration: Agentfull
          RUBY_VERSION: 24

    environment:
      APPVEYOR_AGENTS: true

    before_test:
      - ps: |
          ruby -v
          gem -v
          bundle -v
          type Gemfile.lock
          . .\ci.ps1
          Install-Puppetfile
          Set-WinRMHostConfiguration
          # Make sure Puppet Ruby take precedence over system ruby (pup 5/6)
          $puppet_five_ruby = "C:\Program Files\Puppet Labs\Puppet\sys\ruby\bin"
          $puppet_six_ruby = "C:\Program Files\Puppet Labs\Puppet\puppet\bin"
          [System.Environment]::SetEnvironmentVariable("Path","$puppet_five_ruby;$puppet_six_ruby;" + $ENV:Path, [System.EnvironmentVariableTarget]::Machine)

    test_script:
      - bundle exec rake integration:appveyor_agents
