version: "3"
services:
  boltserver:
    build:
      context: .
      dockerfile: Dockerfile.bolt-server
    ports:
      - "62658:62658"
networks:
  default:
    external:
      name: spec_default

