name: Deploy

on:
  push:
    branches: [master]

env:
  REGISTRY_HOST: pcr-internal.puppet.net
  DOCKER_REGISTRY: pe-and-platform
  DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

jobs:

  deploy:
    name: Deploy bolt-server
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Deploy container
      if: github.ref == 'refs/heads/master'
      run: ./scripts/deploy.sh
