name: Deploy

on:
  push:
    branches: [master]

env:
  REGISTRY_HOST: artifactory.delivery.puppetlabs.net
  DOCKER_REGISTRY: pe-and-platform

jobs:
  deploy:
    name: Deploy bolt-server
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Log in as artifactory docker user
      if: github.ref == 'refs/heads/master'
      uses: azure/docker-login@v1
      with:
        login-server: 'https://artifactory.delivery.puppetlabs.net'
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Deploy bolt-server container
      if: github.ref == 'refs/heads/master'
      run: ./scripts/deploy.sh
