name: Linux

on:
  push:
    branches: [main]
    paths-ignore: ['**.md', '**.erb', 'schemas/*']
  pull_request:
    types: [opened, reopened, edited, synchronize]
    paths-ignore: ['**.md', '**.erb', 'schemas/*']

env:
  BOLT_SUDO_USER: true
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:

  unit:
    name: Unit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - name: Update gems
        run: bundle update
      - name: Pre-test setup
        run: |
          bundle exec r10k puppetfile install
      - name: Unit tests
        run: bundle exec rake tests:unit

  integration:
    name: Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - name: Update gems
        run: bundle update
      - name: Pre-test setup
        run: |
          echo 'runner:runner' | sudo chpasswd
          sudo sh -c "echo 'Defaults authenticate' >> /etc/sudoers"
          sudo sh -c "echo 'runner  ALL=(ALL) PASSWD:ALL' >> /etc/sudoers"
          chmod 0600 spec/fixtures/keys/id_rsa
          docker-compose -f spec/docker-compose.yml build --parallel
          docker-compose -f spec/docker-compose.yml up -d
          bundle exec r10k puppetfile install
      - name: Integration tests
        run: bundle exec rake ci:linux:integration
